// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVagZN42U7OxCbo4bRrDn-mKaLVqWka7k',
    appId: '1:756273477389:web:be429ce7da3515b8186244',
    messagingSenderId: '756273477389',
    projectId: 'call-de',
    authDomain: 'call-de.firebaseapp.com',
    storageBucket: 'call-de.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSgNT91_c9hsoh4LQivszUN6NGmfXmtfA',
    appId: '1:756273477389:android:93ac0ef75dea2555186244',
    messagingSenderId: '756273477389',
    projectId: 'call-de',
    storageBucket: 'call-de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY_l4-HiW1TePs3hF46daEkyDyYLVEsHM',
    appId: '1:756273477389:ios:9ccfe6bb23655756186244',
    messagingSenderId: '756273477389',
    projectId: 'call-de',
    storageBucket: 'call-de.firebasestorage.app',
    iosBundleId: 'com.example.demoApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCY_l4-HiW1TePs3hF46daEkyDyYLVEsHM',
    appId: '1:756273477389:ios:9ccfe6bb23655756186244',
    messagingSenderId: '756273477389',
    projectId: 'call-de',
    storageBucket: 'call-de.firebasestorage.app',
    iosBundleId: 'com.example.demoApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVagZN42U7OxCbo4bRrDn-mKaLVqWka7k',
    appId: '1:756273477389:web:1c2454674ea287bc186244',
    messagingSenderId: '756273477389',
    projectId: 'call-de',
    authDomain: 'call-de.firebaseapp.com',
    storageBucket: 'call-de.firebasestorage.app',
  );
}
